apiVersion: v1
kind: Config
clusters:
- name: "test"
  cluster:
    server: "https://192.168.6.140/k8s/clusters/c-8swnh"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJ2RENDQ\
      VdPZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQkdNUnd3R2dZRFZRUUtFeE5rZVc1aGJXbGoKY\
      kdsemRHVnVaWEl0YjNKbk1TWXdKQVlEVlFRRERCMWtlVzVoYldsamJHbHpkR1Z1WlhJdFkyRkFNV\
      GMyTWpjMApNREV3TkRBZUZ3MHlOVEV4TVRBd01qQXhORFJhRncwek5URXhNRGd3TWpBeE5EUmFNR\
      Vl4SERBYUJnTlZCQW9UCkUyUjVibUZ0YVdOc2FYTjBaVzVsY2kxdmNtY3hKakFrQmdOVkJBTU1IV\
      1I1Ym1GdGFXTnNhWE4wWlc1bGNpMWoKWVVBeE56WXlOelF3TVRBME1Ga3dFd1lIS29aSXpqMENBU\
      VlJS29aSXpqMERBUWNEUWdBRWg3cjNtWXo2REEwUQpSaytrdU1MaTRoSUdKN0Vaa092NjhZV2Jqe\
      G81OGxva1NsY1VKcW9TV0U5c05VWlA2REdieVJFcmdqa0FORktOCjhKa0x5emtIMXFOQ01FQXdEZ\
      1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWUQKVlIwT0JCWUVGT\
      EpWVHRhUSt2RWtqTDBtbXBybWMwSENYYTBDTUFvR0NDcUdTTTQ5QkFNQ0EwY0FNRVFDSUNlNQplZ\
      mZmMlZLZzU2TXFvclBLeVNaVktHaldRZ3h4T0JmMXRuMWFXNTNxQWlBWHB5MEE5VXYvVkt0VGNML\
      3RYMzNqClRwUnJwcWkvLytITlNyMElUZzBpd1E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t"

users:
- name: "test"
  user:
    token: "kubeconfig-u-rfgjgqb7pv:hzfp9xsc6dltmp9hjlv6vlwwg5rwqdbpkz5fpr728m9p4vd6l2mzth"


contexts:
- name: "test"
  context:
    user: "test"
    cluster: "test"

current-context: "test"
